# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f253cc603ae1124e90fdd2b91a06add490986a432cdbb44ee7fa7ab1a7473955dffca29eb448748d2479b00db4645441fcd3dc0184a02a47fd872b31da5deeee

test:
  secret_key_base: c9794c96437638aa89ab706cfe79bccd909a73359196056f17055849775aaa5fea4b3f9a8fb6521051395cc42a4e1e7cb028e673d5049fd96d1e809fb42f1500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
